apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-nest
  namespace: challenge-202502
  labels:
    api-nest: api-nest
spec:
  replicas: 1
  selector:
    matchLabels:
      api-nest: api-nest
  template:
    metadata:
      labels:
        api-nest: api-nest
    spec:
      containers:
        - name: api-nest
          image: api-nest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: api-nest
  namespace: challenge-202502
spec:
  selector:
    api-nest: api-nest
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000